#' @title Add a wedge bond.
#'
#' @description
#' Helper function to add wedge (outside of the plane) bonds connecting atoms.
#'
#' @param result A valid data object generated by \code{ggchemplot1}.
#' @param from_id Numeric. Specifies the \code{atom_id} number of the first atom.
#' @param to_id Numeric. Specifies the \code{atom_id} number of the second atom.
#' @param shorten Numeric. Shortens the wide side of the bond to avoid superposition with the atom layer. Default to 0.28.
#'
#' @return A list as in \code{ggchemplot1}.
#'
#' @import ggplot2
#' @import dplyr
#'
#' @export
add_wedge_bond <- function(result, from_id, to_id, shorten = 0.28) {
  result$bond_coords <- result$bond_coords %>%
    filter(!((
      .data$from == from_id & .data$to == to_id) |
        (.data$from == to_id & .data$to == from_id)))

  new_bond <- data.frame(
    from = as.integer(from_id),
    to = as.integer(to_id),
    order = 1,
    bond_type = "solid",
    shorten = shorten
  )

  result$bond_coords <- bind_rows(result$bond_coords, new_bond)
  result <- rebuild_bond_coords(result)
  return(result)
}
