#' @title AAdd wavy/squiggly line representing protein attachment.
#'
#' @description
#' Helper function to add wavy lines representing protein attachments to user-defined locations.
#'
#' @param result A valid data object generated by \code{ggchemplot1}.
#' @param x_start Numeric. Location in the x-axis where the wave starts.
#' @param y_start Numeric. Location in the y-axis where the wave starts.
#' @param length Numeric. Length of the wave. Default to 1.8.
#' @param angle Numeric. Angle of the wave. Default to 0.
#' @param amplitude Numeric. Amplitude of the wave. Default to 0.15.
#' @param frequency Numeric. Frequency of the wave. Default to 4.
#' @param segments Numeric. Increase to make the wave smoothie. Default to 80.
#' @param linewidth Numeric. Width of the wave line. Default to 1.35.
#' @param label Character. Optional. Add a label to the wave. Useful for protein names. Default to NULL.
#'
#' @return A list as in \code{ggchemplot1}.
#'
#' @import ggplot2
#' @import dplyr
#'
#' @export
add_protein_link <- function(result,
                             x_start,
                             y_start,
                             length = 1.8,
                             angle = 0,
                             amplitude = 0.15,
                             frequency = 4,
                             segments = 80,
                             linewidth = 1.35,
                             label = NULL) {

  rad <- angle * pi / 180

  # Main direction vector
  dx <- length * cos(rad)
  dy <- length * sin(rad)

  # Perpendicular vector for the wave
  px <- -dy
  py <- dx

  t <- seq(0, 1, length.out = segments)

  # Base line + perpendicular wave
  x <- x_start + t * dx + amplitude * sin(t * 2 * pi * frequency) * px
  y <- y_start + t * dy + amplitude * sin(t * 2 * pi * frequency) * py

  wavy_df <- data.frame(x = x, y = y)

  if (is.null(result$protein_links)) result$protein_links <- list()
  result$protein_links[[length(result$protein_links) + 1]] <-
    list(data = wavy_df, linewidth = linewidth)

  # Optional label
  if (!is.null(label)) {
    label_x <- x_start + dx * 1.18
    label_y <- y_start + dy * 1.18
    if (is.null(result$protein_labels)) result$protein_labels <- list()
    result$protein_labels[[length(result$protein_labels)+1]] <-
      data.frame(x = label_x, y = label_y, label = label)
  }

  return(result)
}
