#' @title Add a new bond.
#'
#' @description
#' Helper function to add new bonds connecting atoms.
#'
#' @param result A valid data object generated by \code{ggchemplot1}.
#' @param from_id Numeric. Specifies the \code{atom_id} number of the first atom.
#' @param to_id Numeric. Specifies the \code{atom_id} number of the second atom.
#' @param order Numeric. Specifies the \code{order} number (1 = single, 2 = double, 3 = triple). Default to 1. Independent of the order, only adds a single bond at a time.
#'
#' @return A list as in \code{ggchemplot1}.
#'
#' @import ggplot2
#' @import dplyr
#'
#' @export
add_bond <- function(result, from_id, to_id, order = 1) {
  new_bond <- data.frame(
    from = as.integer(from_id),
    to = as.integer(to_id),
    order = as.integer(order)
  )

  # Add the raw bond
  result$bond_coords <- bind_rows(result$bond_coords, new_bond)

  # Rebuild full bond_coords with coordinates while preserving special columns
  atoms_temp <- result$atoms %>%
    select(.data$atom_id, .data$x, .data$y, .data$symbol)

  result$bond_coords <- result$bond_coords %>%
    # Preserve all special columns
    select(.data$from, .data$to, .data$order,
           any_of(c("bond_type", "shorten_start", "shorten_end",
                    "width", "wedge_thickness", "n_hashes", "colour"))) %>%
    left_join(atoms_temp, by = c("from" = "atom_id")) %>%
    rename(x1 = .data$x, y1 = .data$y, sym1 = .data$symbol) %>%
    left_join(atoms_temp, by = c("to" = "atom_id")) %>%
    rename(x2 = .data$x, y2 = .data$y, sym2 = .data$symbol)

  return(result)
}
