#' @title Add a wedge bond.
#'
#' @description
#' Helper function to add wedge (outside of the plane) bonds connecting atoms.
#'
#' @param result A valid data object generated by \code{ggchemplot1}.
#' @param from_id Numeric. Specifies the \code{atom_id} number of the first atom.
#' @param to_id Numeric. Specifies the \code{atom_id} number of the second atom.
#' @param shorten Numeric vector of length 2. Shortens the beging and start of the bond to avoid superposition with the atom layer. Default to c(0.15, 0.25).
#' @param colour String. Specifies the bond color. Default to "black".
#' @param width Numeric. Specifies the bond width. Default to 0.26.
#'
#' @return A list as in \code{ggchemplot1}.
#'
#' @import ggplot2
#' @import dplyr
#'
#' @export
add_wedge_bond <- function(result, from_id, to_id,
                           shorten = c(0.15, 0.25),   # c(start, end)
                           colour = "black",
                           width = 0.26) {

  result$bond_coords <- result$bond_coords %>%
    filter(!((.data$from == from_id & .data$to == to_id) |
               (.data$from == to_id & .data$to == from_id)))

  new_bond <- data.frame(
    from = as.integer(from_id),
    to = as.integer(to_id),
    order = 1,
    bond_type = "solid",
    shorten_start = shorten[1],
    shorten_end = shorten[2],
    colour = colour,
    width = width
  )

  result$bond_coords <- bind_rows(result$bond_coords, new_bond)
  result <- rebuild_bond_coords(result)
  return(result)
}
