#' @title Add a hashed bond.
#'
#' @description
#' Helper function to add hash (inside of the plane) bonds connecting atoms.
#'
#' @param result A valid data object generated by \code{ggchemplot1}.
#' @param from_id Numeric. Specifies the \code{atom_id} number of the first atom.
#' @param to_id Numeric. Specifies the \code{atom_id} number of the second atom.
#' @param shorten Numeric vector of length 2. Shortens the start and end of the bond to avoid superposition with the atom layer. Default to c(0.15, 0.22).
#' @param colour Character. Specifies the bond color. Default to "black".
#' @param width Numeric. Specifies the bond width. Default to 0.28.
#' @param wedge_thickness Numeric. Specifies the thickness of individual hashes. Default to 0.10.
#' @param n_hashes Numeric. Specifies the number of hashes. Default to 8.
#'
#' @return A list as in \code{ggchemplot1}.
#'
#' @import ggplot2
#' @import dplyr
#'
#' @export
add_hashed_bond <- function(result, from_id, to_id,
                            shorten = c(0.15, 0.22),
                            colour = "black",
                            width = 0.28,
                            wedge_thickness = 0.10,
                            n_hashes = 8) {

  result$bond_coords <- result$bond_coords %>%
    filter(!((.data$from == from_id & .data$to == to_id) |
               (.data$from == to_id & .data$to == from_id)))

  new_bond <- data.frame(
    from = as.integer(from_id),
    to = as.integer(to_id),
    order = 1,
    bond_type = "hashed",
    shorten_start = shorten[1],
    shorten_end = shorten[2],
    colour = colour,
    width = width,
    wedge_thickness = wedge_thickness,
    n_hashes = n_hashes,
    stringsAsFactors = FALSE
  )

  result$bond_coords <- bind_rows(result$bond_coords, new_bond)
  result <- rebuild_bond_coords(result)
  return(result)
}
