#' @title Add a new atom.
#'
#' @description
#' Helper function to add new atoms to user-defined locations.
#'
#' @param result A valid data object generated by \code{ggchemplot1}.
#' @param x Numeric. Location of the atom in the x-axis.
#' @param y Numeric. Location of the atom in the y-axis.
#' @param symbol String. Label for the the atom.
#' @param atom_id Numeric. (Optional). Specifies the \code{atom_id} number. Default to NULL: \code{atom_id} automatically generated.
#' @param color String. Color for the the atom.
#'
#' @return A list as in \code{ggchemplot1}.
#'
#' @import ggplot2
#' @import dplyr
#'
#' @export
add_atom <- function(result, x, y, symbol = "C", atom_id = NULL, color = NULL) {
  if (is.null(atom_id)) {
    atom_id <- max(result$atoms$atom_id) + 1
  }

  new_atom <- data.frame(
    atom_id = as.integer(atom_id),
    x = x,
    y = y,
    symbol = symbol,
    stringsAsFactors = FALSE
  )

  # Add color
  new_atom$default_color <- case_when(
    symbol == "C" ~ "black",
    symbol == "O" ~ "#e31a1c",
    symbol == "N" ~ "#1f78b4",
    symbol == "P" ~ "violet",
    symbol == "S" ~ "#e6ab02",
    symbol == "Fe" ~ "orange",
    TRUE ~ "black"
  )

  new_atom$color <- if (is.null(color)) new_atom$default_color else
    new_atom$color %||% color

  result$atoms <- bind_rows(result$atoms, new_atom)
  return(result)
}
