#' @title Change atom labels
#'
#' @description
#' Helper function to edit atom labels.
#'
#' @param result A valid data object generated by \code{ggchemplot1}.
#' @param atom_id Numeric. Specifies the \code{atom_id} number.
#' @param new_label Character. The new label for the atom.
#'
#' @return A list as in \code{ggchemplot1}.
#'
#' @import ggplot2
#' @import dplyr
#'
#' @export
change_label <- function(result, atom_id, new_label) {
  result$atoms <- result$atoms %>%
    mutate(symbol = ifelse(atom_id == !!atom_id, new_label, .data$symbol))

  if (!is.null(result$h_labels)) {
    result$h_labels <- result$h_labels %>%
      mutate(h_text = ifelse(.data$parent_id == !!atom_id, NA, .data$h_text))
  }
  return(result)
}
