#' @title Delete atom and associated bonds.
#'
#' @description
#' Helper function to delete atoms.
#'
#' @param result A valid data object generated by \code{ggchemplot1}.
#' @param atom_id Numeric. Specifies the \code{atom_id} number.
#'
#' @return A list as in \code{ggchemplot1}.
#'
#' @import ggplot2
#' @import dplyr
#'
#' @export
delete_atom <- function(result, atom_id) {
  result$atoms <- result$atoms %>% filter(atom_id != !!atom_id)
  result$bond_coords <- result$bond_coords %>%
    filter(.data$from != !!atom_id & .data$to != !!atom_id)
  if (!is.null(result$h_labels)) {
    result$h_labels <- result$h_labels %>% filter(.data$parent_id != !!atom_id)
  }
  return(result)
}
