#' @title Delete bonds.
#'
#' @description
#' Helper function to delete bonds.
#'
#' @param result A valid data object generated by \code{ggchemplot1}.
#' @param from_id Numeric. Specifies the \code{from_id} number of the bond.
#' @param to_id Numeric. Specifies the \code{to_id} number of the bond.
#'
#' @return A list as in \code{ggchemplot1}.
#'
#' @export
delete_bond <- function(result, from_id, to_id) {
  result$bond_coords <- result$bond_coords %>%
    filter(!((.data$from == from_id & .data$to == to_id) |
               (.data$from == to_id & .data$to == from_id)))
  return(result)
}
