#' @title Draw Chemical Structures with ggplot2
#'
#' @description
#' Creates high-quality 2D visualizations of chemical structures
#' using ggplot2. Supports collapsed hydrogens, stereochemical bonds, protein
#' links, and extensive customization.
#'
#' @param result A valid data object generated by \code{ggchemplot1}.
#' @param title String. Optional title for the plot.
#' @param label_padding Numeric. Amount of padding around the molecule to prevent
#'        labels from being cut off. Higher values add more white space.
#'        Default is 0.6.
#' @param show_atom_circles Logical. Whether to draw circles around atoms.
#' @param hide_carbon_circles Logical. Whether to hide circles around carbon atoms. Useful for showing organic compounds.
#' @param circle_stroke Numeric. Thickness of the atom circle border.
#' @param show_atom_labels Logical. Whether to show atom labels.
#' @param hide_carbon_labels Logical. Whether to hide labels for carbon atoms.
#' @param bond_width Numeric. Thickness of the bonds.
#' @param atom_size Numeric. Size of the atom circles.
#' @param label_size Numeric. Size of the atom labels.
#' @param double_bond_offset Numeric. Offset distance for drawing double and triple bonds.
#' @param paint_it_black Logical. If \code{TRUE}, overrides colors to make all atoms black.
#' @param show_ids Logical. Whether to show atom and bond ids. Helps when polishing the visualization.
#' @param H_offset Numeric vector of length 2. Controls the distance of collapsed
#'        hydrogen labels (first value for single H, second for H2/H3).
#'        Only used when \code{collapse_hydrogens = TRUE}.
#'
#' @return A ggplot object.
#'
#' @import ggplot2
#' @import dplyr
#'
#' @export
ggchemplot2 <- function(result,
                        title = NULL,
                        label_padding = NULL,
                        show_atom_circles = NULL,
                        hide_carbon_circles = NULL,
                        circle_stroke = NULL,
                        show_atom_labels = NULL,
                        hide_carbon_labels = NULL,
                        bond_width = NULL,
                        atom_size = NULL,
                        label_size = NULL,
                        double_bond_offset = NULL,
                        paint_it_black = NULL,
                        show_ids = FALSE,
                        H_offset = FALSE) {

  # Use stored parameters as defaults
  pms <- result$params

  title               <- if (!is.null(title)) title else pms$title
  label_padding       <- if (!is.null(label_padding)) label_padding else pms$label_padding %||% 1.2
  show_atom_circles   <- if (!is.null(show_atom_circles)) show_atom_circles else pms$show_atom_circles %||% TRUE
  hide_carbon_circles <- if (!is.null(hide_carbon_circles)) hide_carbon_circles else pms$hide_carbon_circles %||% TRUE
  circle_stroke       <- if (!is.null(circle_stroke)) circle_stroke else pms$circle_stroke %||% 1.0
  show_atom_labels    <- if (!is.null(show_atom_labels)) show_atom_labels else pms$show_atom_labels %||% TRUE
  hide_carbon_labels  <- if (!is.null(hide_carbon_labels)) hide_carbon_labels else pms$hide_carbon_labels %||% TRUE
  bond_width          <- if (!is.null(bond_width)) bond_width else pms$bond_width %||% 1.22
  atom_size           <- if (!is.null(atom_size)) atom_size else pms$atom_size %||% 4.25
  label_size          <- if (!is.null(label_size)) label_size else pms$label_size %||% 3.1
  double_bond_offset  <- if (!is.null(double_bond_offset)) double_bond_offset else pms$double_bond_offset %||% 0.105
  paint_it_black  <- if (!is.null(paint_it_black)) double_bond_offset else pms$paint_it_black %||% "black"
  H_offset  <- if (!is.null(H_offset))
    H_offset else pms$H_offset %||% c(0.45, 0.55)

  atoms <- result$atoms
  bond_coords <- result$bond_coords

  p <- ggplot()

  # ===================== BONDS (Normal + Wedge + Hashed) ======================
  if (nrow(bond_coords) > 0) {

    # Ensure bond_type column exists
    if (!"bond_type" %in% names(bond_coords)) {
      bond_coords$bond_type <- NA_character_
    }

    # Normal bonds
    normal_bonds <- bond_coords %>% filter(is.na(.data$bond_type))
    if (nrow(normal_bonds) > 0) {
      p <- p + geom_segment(data = normal_bonds,
                            aes(x = .data$x1, y = .data$y1,
                                xend = .data$x2, yend = .data$y2),
                            linewidth = bond_width, color = "black")
    }

    # Special bonds (Wedge + Hashed)
    special_bonds <- bond_coords %>% filter(!is.na(.data$bond_type))
    if (nrow(special_bonds) > 0) {
      p <- p + geom_wedge(data = special_bonds,
                          aes(x1 = .data$x1, y1 = .data$y1,
                              x2 = .data$x2, y2 = .data$y2,
                              wedgetype = .data$bond_type,
                              shorten = .data$shorten),
                          width = 0.26,
                          wedge_thickness = 0.12)
    }

    # PROTEIN LINKS (Wavy lines)
    if (!is.null(result$protein_links) && length(
      result$protein_links) > 0) {
      for (link in result$protein_links) {
        p <- p + geom_path(data = link$data,
                           aes(x = .data$x, y = .data$y),
                           linewidth = link$linewidth %||% 1.3,
                           color = "black")
      }
    }

    # Optional labels
    if (!is.null(result$protein_labels) && length(result$protein_labels) > 0) {
      labels_df <- do.call(rbind, result$protein_labels)
      p <- p + geom_text(data = labels_df,
                         aes(x = .data$x, y = .data$y, label = .data$label),
                         size = 4.2,
                         fontface = "bold",
                         color = "black")
    }

  }

  # ====================== MULTIPLE BONDS - Locally Aware Offset ======================
  # Handling double/triple bonds
  multi_bonds <- bond_coords %>% filter(order > 1)
  if (nrow(multi_bonds) > 0) {
    offset_dist <- double_bond_offset

    multi_bonds <- multi_bonds %>%
      rowwise() %>%
      mutate(
        dx = .data$x2 - .data$x1, dy = .data$y2 - .data$y1,
        len = sqrt(.data$dx^2 + .data$dy^2),
        ux1 = ifelse(.data$len > 1e-6, -.data$dy / .data$len, 0),
        uy1 = ifelse(.data$len > 1e-6,  .data$dx / .data$len, 0),
        ux2 = -.data$ux1, uy2 = -.data$uy1,
        mid_x = (.data$x1 + .data$x2)/2, mid_y = (.data$y1 + .data$y2)/2,
        side1_score = sum(sqrt((atoms$x - (.data$mid_x + .data$ux1*0.8))^2 +
                                 (atoms$y - (.data$mid_y + .data$uy1*0.8))^2) < 3.5),
        side2_score = sum(sqrt((atoms$x - (.data$mid_x + .data$ux2*0.8))^2 +
                                 (atoms$y - (.data$mid_y + .data$uy2*0.8))^2) < 3.5),
        chosen_ux = ifelse(.data$side1_score >= .data$side2_score, .data$ux1, .data$ux2),
        chosen_uy = ifelse(.data$side1_score >= .data$side2_score, .data$uy1, .data$uy2),
        off_x = .data$chosen_ux * offset_dist,
        off_y = .data$chosen_uy * offset_dist
      ) %>%
      ungroup()

    p <- p + geom_segment(data = multi_bonds,
                          aes(x = .data$x1 + .data$off_x,
                              y = .data$y1 + .data$off_y,
                              xend = .data$x2 + .data$off_x,
                              yend = .data$y2 + .data$off_y),
                          linewidth = bond_width * 0.78, color = "black")

    triples <- multi_bonds %>% filter(order >= 3)
    if (nrow(triples) > 0) {
      p <- p + geom_segment(data = triples,
                            aes(x = .data$x1 - .data$off_x,
                                y = .data$y1 - .data$off_y,
                                xend = .data$x2 - .data$off_x,
                                yend = .data$y2 - .data$off_y),
                            linewidth = bond_width * 0.78, color = "black")
    }
  }

  # Atom circles
  atoms_circle <- if (hide_carbon_circles) atoms %>%
    filter(.data$symbol != "C") else atoms
  if (show_atom_circles && nrow(atoms_circle) > 0) {
    p <- p + geom_point(data = atoms_circle,
                        aes(x = .data$x, y = .data$y),
                        color = atoms_circle$color,
                        fill = "white",
                        size = atom_size,
                        shape = 21,
                        stroke = circle_stroke)
  }

  # ================= LABELS: Heavy Atom + Smart H Positioning =================
  if (show_atom_labels) {
    atoms_label <- atoms
    if (hide_carbon_labels) {
      atoms_label <- atoms_label %>% filter(.data$symbol != "C")
    }

    # Main heavy atoms
    p <- p + geom_text(data = atoms_label,
                       aes(x = .data$x, y = .data$y,
                           label = .data$symbol),
                       size = label_size,
                       fontface = "bold",
                       color = atoms_label$color)

    # H labels with different offsets for H vs H2/H3
    if (!is.null(result$h_labels) && nrow(result$h_labels) > 0) {
      h_labels <- result$h_labels

      # Calculate bond direction
      connected <- bond_coords %>%
        filter(.data$from %in% h_labels$parent_id |
                 .data$to %in% h_labels$parent_id) %>%
        mutate(
          atom_id = ifelse(.data$from %in% h_labels$parent_id,
                           .data$from, .data$to),
          partner_x = ifelse(.data$from %in% h_labels$parent_id,
                             .data$x2, .data$x1)
        ) %>%
        left_join(h_labels %>% select(.data$parent_id, .data$x),
                  by = c("atom_id" = "parent_id")) %>%
        group_by(.data$atom_id) %>%
        summarise(
          bond_dx = mean(.data$partner_x - .data$x, na.rm = TRUE),
          .groups = "drop"
        )

      h_labels <- h_labels %>%
        left_join(connected, by = c("parent_id" = "atom_id")) %>%
        mutate(
          # Different distance based on label length
          offset_dist = ifelse(.data$nH == 1, H_offset[1], H_offset[2]),

          # Direction logic:
          # bond_dx > 0  → bond coming from right  → put H on the left  (HO-)
          # bond_dx < 0  → bond coming from left → put H on the right   (-OH)
          hx = .data$x + ifelse(is.na(.data$bond_dx) | .data$bond_dx > 0,
                          -offset_dist,
                          +offset_dist),
          # For future improvement: handle H stacked below/above heteroatom
          hy = .data$y
        )

      p <- p + geom_text(data = h_labels,
                         aes(x = .data$hx, y = .data$hy,
                             label = .data$h_text),
                         parse = TRUE,
                         size = label_size,
                         fontface = "bold",
                         color = "black")
    }
  }

  # OPTIONAL: SHOW IDS FOR EDITING
  if (show_ids) {
    # Atom IDs
    p <- p + geom_text(data = atoms,
                       aes(x = .data$x + 0.25, y = .data$y + 0.25,
                           label = .data$atom_id),
                       size = 5, color = "red", fontface = "bold")

    # Bond IDs (midpoint)
    if (nrow(bond_coords) > 0) {
      bond_mid <- bond_coords %>%
        mutate(mid_x = (.data$x1 + .data$x2)/2,
               mid_y = (.data$y1 + .data$y2)/2,
               bond_id = row_number())

      p <- p + geom_text(data = bond_mid,
                         aes(x = .data$mid_x, y = .data$mid_y,
                             label = .data$bond_id),
                         size = 5, color = "blue", fontface = "bold")
    }
  }

  p <- p +
    coord_fixed(ratio = 1) +
    theme_void() +
    theme(plot.title = element_text(hjust = 0.5, size = 14, face = "bold"),
          plot.margin = margin(10, 10, 10, 10, "mm")) +
    labs(title = title)

  # ====================== MANUAL LABEL PADDING ======================
  if (nrow(atoms) > 0) {
    x_range <- range(atoms$x, na.rm = TRUE)
    y_range <- range(atoms$y, na.rm = TRUE)

    p <- p +
      xlim(x_range[1] - label_padding, x_range[2] + label_padding) +
      ylim(y_range[1] - label_padding, y_range[2] + label_padding)
  }

  return(p)
}
