#' @title Save 2D chemical structure with consistent bond-length scale
#'
#' @description
#' Saves a ggplot chemical structure so that the median bond has a defined
#' physical length (in centimetres).
#'
#' @param result A valid data object generated by \code{ggchemplot1}.
#' @param plot A ggplot object. If \code{NULL}, \code{result$plot} is used.
#' @param filename Output filename. Extension determines the format
#'        (\code{.svg} recommended).
#' @param bond_length Desired physical length of the median bond in cm.
#'        Default is 1.
#' @param dpi Resolution used only for raster formats (PNG). Ignored for SVG.
#' @param bg Background colour. Default is \code{"transparent"}.
#' @param ... Additional arguments passed to \code{ggplot2::ggsave}.
#'
#' @return The path of the saved file (invisibly).
#'
#' @import xml2
#' @importFrom stats mad
#'
#' @export
save_chemplot <- function(result,
                          plot = NULL,
                          filename,
                          bond_length = 1,
                          dpi = 600,
                          bg = "transparent",
                          ...) {

  if (is.null(result$atoms) || nrow(result$atoms) == 0) {
    stop("No atom data found in result$atoms")
  }

  if (is.null(plot)) {
    if (is.null(result$plot)) {
      stop("No plot supplied and result$plot is NULL. Run ggchemplot2() first.")
    }
    plot <- result$plot
  }

  atoms <- result$atoms
  bonds <- result$bond_coords

  # ----- median bond length in data units -----
  if (!is.null(bonds) && nrow(bonds) > 0) {
    bond_lengths <- sqrt(
      (bonds$x2 - bonds$x1)^2 +
        (bonds$y2 - bonds$y1)^2
    )

    bond_lengths <- bond_lengths[is.finite(bond_lengths) & bond_lengths > 0]

    if (length(bond_lengths) > 0) {
      med <- median(bond_lengths)
      mad_val <- mad(bond_lengths, center = med, constant = 1)

      # Keep bonds within 3 MAD of the median
      if (mad_val > 0) {
        typical_bonds <- bond_lengths[
          abs(bond_lengths - med) <= 3 * mad_val
        ]
      } else {
        typical_bonds <- bond_lengths
      }

      median_bond <- median(typical_bonds)
    } else {
      median_bond <- 1.0
    }
  } else {
    median_bond <- 1.0
  }

  if (median_bond < 1e-6) {
    warning("Median bond length is almost zero; using 1.0 as fallback")
    median_bond <- 1.0
  }

  # ----- data spans -----
  x_span <- diff(range(atoms$x, na.rm = TRUE))
  y_span <- diff(range(atoms$y, na.rm = TRUE))
  if (x_span < 1e-6) x_span <- 1
  if (y_span < 1e-6) y_span <- 1

  # ----- physical size so that median bond = bond_length -----
  scale_cm_per_unit <- bond_length / median_bond
  width_cm  <- x_span * scale_cm_per_unit
  height_cm <- y_span * scale_cm_per_unit

  # small safety margin
  margin_factor <- 1.08
  width_cm  <- width_cm  * margin_factor
  height_cm <- height_cm * margin_factor

  # ----- filename -----
  if (!grepl("\\.(svg|png|pdf|ps|eps)$", filename, ignore.case = TRUE)) {
    filename <- paste0(filename, ".svg")
  }
  ext <- tolower(tools::file_ext(filename))

  message(sprintf(
    "Median bond = %.3f data units - %.2f cm | Size: %.2f x %.2f cm (%s)",
    median_bond, bond_length, width_cm, height_cm, toupper(ext)
  ))

  # ----- save -----
  ggplot2::ggsave(
    filename = filename,
    plot     = plot,
    width    = width_cm,
    height   = height_cm,
    units    = "cm",
    dpi      = dpi,
    bg       = bg,
    ...
  )

  # ----- post-process SVG: remove background <rect> only -----
  if (ext == "svg") {
    .clean_svg_background(filename)
  }

  invisible(filename)
}

# -----------------------------------------------------------------
# Internal helper - removes background rectangle
# -----------------------------------------------------------------
.clean_svg_background <- function(svg_file) {

  if (!requireNamespace("xml2", quietly = TRUE)) {
    message("Package 'xml2' not available - SVG background was not removed")
    return(invisible(NULL))
  }

  doc  <- xml2::read_xml(svg_file)
  root <- xml2::xml_root(doc)

  # Find all <rect> elements safely
  rects <- xml2::xml_find_all(root, ".//*[local-name()='rect']")

  removed <- 0L

  for (rect in rects) {

    # ---------------------------------------------------------------
    # IMPORTANT: skip rectangles that are part of clipPath or defs
    # ---------------------------------------------------------------
    parent <- xml2::xml_parent(rect)
    parent_name <- xml2::xml_name(parent)

    if (parent_name %in% c("clipPath", "defs")) {
      next
    }

    # also skip if any ancestor is a clipPath
    ancestors <- xml2::xml_find_all(rect, "ancestor::*[local-name()='clipPath']")
    if (length(ancestors) > 0) next

    # ---------------------------------------------------------------
    # Now decide if this rect is a background
    # ---------------------------------------------------------------
    w     <- xml2::xml_attr(rect, "width")
    h     <- xml2::xml_attr(rect, "height")
    style <- xml2::xml_attr(rect, "style") %||% ""
    fill  <- xml2::xml_attr(rect, "fill")
    stroke<- xml2::xml_attr(rect, "stroke")

    style_low <- tolower(style)

    is_background <- FALSE

    # classic full-canvas background
    if (!is.na(w) && (w == "100%" || w == "100")) is_background <- TRUE
    if (!is.na(h) && (h == "100%" || h == "100")) is_background <- TRUE

    # large absolute rectangles with no visible stroke/fill
    if (!is.na(w) && !is.na(h)) {
      w_num <- suppressWarnings(as.numeric(gsub("[^0-9.]", "", w)))
      h_num <- suppressWarnings(as.numeric(gsub("[^0-9.]", "", h)))
      if (!is.na(w_num) && !is.na(h_num) && w_num > 50 && h_num > 50) {
        is_background <- TRUE
      }
    }

    no_stroke <- grepl("stroke:\\s*none", style_low) ||
      grepl("stroke-width:\\s*0", style_low) ||
      (!is.na(stroke) && stroke == "none")

    no_fill <- grepl("fill:\\s*none", style_low) ||
      (!is.na(fill) && fill %in% c("none", "transparent")) ||
      is.na(fill) || is.null(fill)

    if (no_stroke && no_fill) is_background <- TRUE

    if (is_background) {
      xml2::xml_remove(rect)
      removed <- removed + 1L
    }
  }

  xml2::write_xml(doc, svg_file)

  if (removed > 0) {
    message(sprintf("SVG post-processing: removed %d background rectangle(s)", removed))
  } else {
    message("SVG post-processing: no removable background rectangles found")
  }

  invisible(NULL)
}
